[package]
name = "sc_paymaster"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.8.0"

[dev-dependencies]
cairo_test = "2.8.0"

[tool.scarb]
cairo = "2.8.0"

[[target.starknet-contract]]
contracts = ["src/lib.cairo"] 